### ISSUE TITLE
Reference not work

### ISSUE THREAD

**Issue by alexz-kh** [lnoor/sphinx-jsonschema#17]
Hello, i'm trying to build rst using  schema with "$ref" structure, and for some reason my references always undefined:
```
assembling single document... services/catalog <unknown>:1: WARNING: undefined label: #/definitions/bind (if the link has no caption the label must precede a section header)
<unknown>:1: WARNING: undefined label: #/definitions/bz (if the link has no caption the label must precede a section header)

```
Exact jsonschema: 

```
title: server role
description: "server configurathion"
type: object
additionalProperties: false

required:
- enabled
- user

properties:
  enabled:
    description: |-
      Enables server configurathion.
    type: boolean
  bind:
    description: Specifies servcive listen on configurathion.
    type: object
    properties:
      "test1": { "$ref": "#/definitions/bind" }
  bindtest2:
    description: Specifies servcive listen on configurathion.
    type: object
    "$ref": '#/definitions/bz'


definitions:
  bind:
    '$$target': [ '#/definitions/bind' , "#/definitions/bz" ]
    type: object
    properties:
      port:
        description: |-
          Specifies the local addresses should listen on.
        type: integer
      address:
        description: Specifies the port on which the server listens for connections. Multiple options are permitted.
        type: string
        example: 127.0.0.1 192.168.1.1
```

Version list 
```
pip freeze |grep -i "sphinx\|yaml"
PyYAML==3.12
Sphinx==1.6.6
sphinx-jsonschema==1.4
sphinxcontrib-websupport==1.0.1
```

Could you suggest me somthing ?)
