### ISSUE TITLE
Schema doesn't get built unless there is something after it

### ISSUE THREAD

**Issue by smithis7** [lnoor/sphinx-jsonschema#60]
I was trying to include a schema (written in YAML) in my documentation (built with Sphinx), but it did not work unless there was something under the ```jsonschema``` directive.

For example, if I put in my RST file:
```
.. jsonschema:: example1.yml

.. jsonschema:: example2.yml
```
only example1 would build. If the document ended with ```.. jsonschema:: example1.yml```, it would not build, but if it was
```
.. jsonschema:: example1.yml

example text
```
it would build. If this is not just a problem on my end, this may be something you want to fix or document.

**Comment by lnoor** [comment]
The only way I could reproduce this is when the yaml file has errors in it.
Could you verify the correctness of your yaml file and let me know the result.

sphinx-jsonschema will try to read a file using pyyaml. When this fails it silently falls back to json.

I did notice something that could be an issue:
sphinx-jsonschema silently converts `\\(` and `\\)` character sequences to `\\\\(` and `\\\\)`; this is probably an error.

Does your yaml file contain sequences like `\\(` or `\\)`? If so, do you get output when you (temporarily) remove these sequences?

**Comment by smithis7** [comment]
I'm so sorry for the extremely late response. Here is an example file for which this problem occurred:
```yaml
number: 1
additionalProperties: false
properties:
  property1:
    type: string
    default: "property1"
    description: A string
  property2:
    type: boolean
    default: false
    description: True or False
```
