### ISSUE TITLE
Underscores escaped in examples output

### ISSUE THREAD

**Issue by ryan-lane** [lnoor/sphinx-jsonschema#74]
I'm using sphinx markup in examples, and it's escaping content with underscores with `\_`.

Example:

Input:

```
.. code-block:: yaml

     env:
        base:
          common:
            - name: HOST
               value: "0.0.0.0"
            - name: PORT
               value: "8080"
            - name: NEO4J_URI
               value: "bolt://test-neo4j:7687"
          user-watcher:
            - name: FLASK_APP
               value: reporting.user_watcher
```

Output:

```
env:
  base:
    common:
      - name: HOST
        value: "0.0.0.0"
      - name: PORT
        value: "8080"
      - name: NEO4J\_URI
        value: "bolt://test-neo4j:7687"
    user-watcher:
      - name: FLASK\_APP
        value: reporting.user\_watcher
 ```
 
 Is there some way to avoid having the examples escaped?
